global:
  resolve_timeout: 5m
route:
  group_wait: 10s
  group_interval: 10s
  group_by: [job]
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - receiver: 'web.hook'
      group_wait: 10s
      match_re:
        job: 'mifi-.*'
receivers:
  - name: 'default'
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:35411/alert'
