apiVersion: v1
kind: Service
metadata:
  name: mariadbsvc
spec:
  selector:
    app: mariadbsts
  ports:
    - port: 8080
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadbsts
  labels:
    app: mariadbsts
spec:
  replicas: 1
  serviceName: mariadbsvc
  template:
    metadata:
      name: mariadbsts
      labels:
        app: mariadbsts
    spec:
      containers:
        - name: mariadbsts
          image: mariadb:10.5.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            # 创建数据库用户密码
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: TZ
              value: Asia/Shanghai
            # 创建数据库
            - name: MYSQL_DATABASE
              value: test
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadbpvc
  selector:
    matchLabels:
      app: mariadbsts
