#version: "2.4"
#volumes:
#  helloapp:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ~/Downloads/mifi_hello/

services:
  mifi-prometheus:
    image: helloapp:v1
    ports:
      - "8080:8080"
    networks:
      - chris_net
    volumes:
#      - helloapp:/home/work/helloapp/
      - ~/Downloads/mifi_hello/:/home/work/helloapp/
    restart: always

networks:
  chris_net:
    driver: bridge
