#docker-compose命令使用root用户创建目录
version: "2.4"
volumes:
  helloapp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Downloads/mifi_hello/
services:
  hello-demo:
    image: hello-demo:1.0.0
    ports:
      - "8080:8080"
    networks:
      - chris_net
    volumes:
      #      - helloapp:/home/work/helloapp/
      - helloapp:/home/work/helloapp/
    restart: always
networks:
  chris_net:
    driver: bridge
