apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: chris
  labels:
    app: grafana-label
spec:
  containers:
    - name: grafana-ppp
      image: grafana/grafana:latest
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
