server:
  port: 9411
management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello-gateway
          uri: https://leetcode.com/
          predicates:
            - Path=/problemset/*
          filters:
            - StripPrefix=1
